# run `brew bundle`
install ack
install ansible
install autoconf
install automake
install axel
install boost
install cloog
install cmake
install ctags
install curl-ca-bundle
install emacs
install fftw
install freetype
install fswatch
install gd
install gettext
install gfortran
install git
install gmp
install gnu-sed
install gnupg
install gnuplot
install icu4c
install isl
install jpeg
install leiningen
install lesspipe
install libevent
install libgpg-error
install libksba
install libmpc
install libpng
install libtool
install libxml2
install libxslt
install libyaml
install lua
install mpfr
install mutt
install node
install ntfs-3g
install openssl
install ossp-uuid
install p7zip
install pcre
install phantomjs
install pkg-config
install postgresql
install mysql
install readline
install reattach-to-user-namespace
install source-highlight
install sqlite
install szip
install tbb
install terminal-notifier
install texinfo
install ag
install tig
install tmux
install unrar
install wget
install wrk
install z

#---
#install drip
#install octave
#install imagemagick
#install mercurial
#install paperkey
#install solr
#install tokyo-cabinet
#install suite-sparse
#install graphicsmagick
#install hadoop
#install hbase
#install hdf5
#install httrack
#install qhull
#install qrencode
#install qrupdate
