# run `brew bundle`
install ack
install ansible
install apple-gcc42
install arpack
install autoconf
install automake
install axel
install boost
install cloog
install cmake
install ctags
install curl-ca-bundle
install drip
install emacs
install fftw
install freetype
install fswatch
install fuse4x
install fuse4x-kext
install gd
install gettext
install gfortran
install git
install gmp
install gnu-sed
install gnupg
install gnuplot
install graphicsmagick
install hadoop
install hbase
install hdf5
install httrack
install icu4c
install imagemagick
install isl
install jpeg
install leiningen
install lesspipe
install libevent
install libgpg-error
install libksba
install libmpc
install libpng
install libtool
install libxml2
install libxslt
install libyaml
install lua
install mercurial
install mpfr
install mutt
install node
install ntfs-3g
install octave
install openssl
install ossp-uuid
install p7zip
install paperkey
install pcre
install phantomjs
install pkg-config
install postgresql
install mysql
install qhull
install qrencode
install qrupdate
install readline
install reattach-to-user-namespace
install solr
install source-highlight
install sqlite
install suite-sparse
install szip
install tbb
install terminal-notifier
install texinfo
install the-silver-searcher
install tig
install tmux
install tokyo-cabinet
install unrar
install wget
install wrk
install z
